`
with(this){
    return _c('div',
    {
        attrs:{\"id\":\"app\"}
    },
    [
        _c('app-slot',
        {
            scopedSlots:_u(
                [
                    {
                        key:\"header\",
                        fn:function(){
                            return [
                                _c('div',
                                    [
                                        _v(\"header\")
                                    ]
                                )
                            ]
                        },
                        proxy:true
                    },
                    {
                        key:\"footer\",
                        fn:function(){
                            return [
                                _c('div',
                                    [
                                        _v(\"footer\")
                                    ]
                                )
                            ]},
                        proxy:true
                    }
                ]
            )
        },
        [
            _v(\" \"),
            _c('div',
                [
                    _v(\"default\")
                ]
            )
        ]
    )
],
1
)
}
`